# Generated by Django 5.2.8 on 2025-12-01 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('toll', 'Toll'), ('maintenance', 'Maintenance'), ('food', 'Food'), ('accommodation', 'Accommodation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_photo', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('to_driver', 'To Driver'), ('from_driver', 'From Driver'), ('to_owner', 'To Owner'), ('from_owner', 'From Owner')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='transfers/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_contact', models.CharField(max_length=100)),
                ('pickup_phone', models.CharField(max_length=15)),
                ('delivery_location', models.CharField(max_length=255)),
                ('delivery_contact', models.CharField(max_length=100)),
                ('delivery_phone', models.CharField(max_length=15)),
                ('pickup_date', models.DateTimeField()),
                ('estimated_delivery_date', models.DateTimeField()),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('load_type', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in tons', max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('waybill', models.FileField(blank=True, null=True, upload_to='documents/waybills/')),
                ('lr_copy', models.FileField(blank=True, null=True, upload_to='documents/lr/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='documents/other/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_assigned', 'Order Assigned'), ('order_status_changed', 'Order Status Changed'), ('expense_added', 'Expense Added'), ('money_transferred', 'Money Transferred'), ('document_uploaded', 'Document Uploaded'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_app.expense')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_app.moneytransfer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='transport_app.transportationorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='transport_app.transportationorder'),
        ),
        migrations.AddField(
            model_name='expense',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='transport_app.transportationorder'),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('axle_count', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('rc_document', models.FileField(blank=True, null=True, upload_to='documents/rc/')),
                ('rc_expiry', models.DateField()),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='documents/insurance/')),
                ('insurance_expiry', models.DateField()),
                ('pollution_certificate', models.FileField(blank=True, null=True, upload_to='documents/pollution/')),
                ('pollution_expiry', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Capacity in tons', max_digits=10)),
                ('fuel_type', models.CharField(default='diesel', max_length=20)),
                ('current_mileage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trucks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_trucks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_app.truck'),
        ),
    ]
