# Generated by Django 4.2 on 2025-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationorder',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
